name: Gitee repos mirror action
on:
  schedule:
    # 每天北京时间4点同步
    - cron:  '0 20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github mate-desktop repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/mate-desktop
        dst: gitee/mate-desktop
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: org
